// TODO: Include packages needed for this application
import inquirer from "inquirer";
import fs from "fs";
import generateMarkDown from './utils/generateMarkdown.mjs';

// TODO: Create an array of questions for user input
const questions = [
    {
        type: "input",
        name: "title",
        message: "What is the title of your project?",
        validate: function (value) { return value.length > 0 ? true : "Please enter a title"; }
    },
    {
        type: "input",
        name: "description",
        message: "Provide a short description explaining the what, why, and how of your project.",
        validate: function (value) { return value.length > 0 ? true : "Please enter a short description"; }
    },
    {
        type: "input",
        name: "installation",
        message: "Please enter instructions on how to install your project.",
        validate: function (value) { return value.length > 0 ? true : "Please enter instructions on how to install your project"; }
    },
    {
        type: "input",
        name: "usage",
        message: "Please enter instructions on how to use your project.",
        validate: function (value) { return value.length > 0 ? true : "Please enter instructions on how to use your project"; }
    },
    {
        type: "input",
        name: "tests",
        message: "Please enter instructions on how to run tests for your project.",
        validate: function (value) { return value.length > 0 ? true : "Please enter instructions on how to run tests for your project"; }
    },
    {
        type: "input",
        name: "contributing",
        message: "Please enter instructions on how to contribute to your project.",
        validate: function (value) { return value.length > 0 ? true : "Please enter instructions on how to contribute to your project"; }
    },
    {
        type: "input",
        name: "questions",
        message: "Please enter instructions on how to contact you for any questions.",
        validate: function (value) { return value.length > 0 ? true : "Please enter instructions on how to contact you for any questions"; }
    },
    {
        type: "list",
        name: "license",
        message: "What kind of license should your project have?",
        choices: [
            "GNU AGPLv3",
            "GNU GPLv3",
            "GNU LGPLv3",
            "Mozilla Public License 2.0",
            "Apache License 2.0",
            "MIT License",
            "Boost Software License 1.0",
            "The Unlicense",
            "None"
        ],
    }
];

// TODO: Create a function to write README file
// TODO: Create a function to initialize app
async function init() {
    try {
        //Get user input from questions array
        const answers = await inquirer.prompt(questions)
        //Get user answers from answers object and pass them to generateMarkDown function.
        .then(answers => {JSON.stringify(answers)})
        .then(answers => {generateMarkDown(answers)})
        .then(answers => {console.log(answers)})
        .catch(error => {console.log(error)});
        //Create output folder if it doesn't exist
        if (!fs.existsSync('./output')) {
            fs.mkdirSync('./output');
        } else {
            console.log('Output folder already exists');
        } //Write markdown file generated by generateMarkDown to output folder
        fs.writeFileSync('./output/README.md', answers);
        console.log('Successfully created README.md');
    } catch (error) {
        console.log(error);
    }
}
init();